### ISSUE TITLE
Поддержка SNI?

### ISSUE THREAD

**Issue by unreturned** [yandex-money/yandex-money-joinup#10]
[по технологии SNI. В настоящий момент наша платежная система не поддерживает этот режим (поддержка ожидается примерно в четвертом квартале 2017 года). ](https://github.com/yandex-money/yandex-money-joinup/blame/master/demo/031%20%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA.md#L27)

Есть новости о поддержке?

Спасибо.

**Comment by unreturned** [comment]
@mckeydonelly Пожалуйста, подскажите по вопросу выше. Спасибо!

**Comment by tuniyants** [comment]
Кажется, поддержка SNI осуществляется с января-февраля прошлого года. 
Есть сомнения? Приведите пример, пожалуйста.

**Comment by mckeydonelly** [comment]
@unreturned добрый день!

Если говорить про наш новый API Кассы (https://kassa.yandex.ru/docs/checkout-api/#ispol-zowanie-api), то поддержка есть из коробки.
Если же про протокол уведомлений (https://tech.yandex.ru/money/doc/payment-solution/About-docpage/), то нет.

**Comment by unreturned** [comment]
Спасибо!
